apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - git:
        repoURL: https://github.com/jbla9028/applicationset.git
        revision: HEAD
        files:
        - path: "examples/git-generator-files-discovery/cluster-config/**/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-guestbook'
    spec:
      project: c4e8568d
      source:
        repoURL: https://github.com/jbla9028/applicationset.git
        targetRevision: HEAD
        path: "examples/git-generator-files-discovery/apps/guestbook"
      destination:
        server: '{{cluster.address}}'
        #server: '{{cluster.address}}'
        namespace: guestbook
      syncPolicy:
        automated: {}
